import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'StackKit App',
  description: 'Generated by create-stackkit-app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.Node;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
